<?php require __DIR__ . '/../partials/dashboard-head.php'; ?>
<div class="dash-head" style="display:flex;justify-content:space-between;align-items:center;gap:12px"><div><h1>V&#7853;t t&#432; phi&#7871;u b&#7843;o h&#224;nh</h1><div style="font-size:13px;color:#667085;margin-top:4px"><?= e($case['case_code']) ?> · <?= e($case['product_name']) ?></div></div><a class="btn btn-outline-navy" href="/admin/warranties">Quay l&#7841;i b&#7843;o h&#224;nh</a></div>
<?php foreach(getFlash() as $message): ?><div class="alert alert-<?= e($message['type']) ?>"><?= e($message['message']) ?></div><?php endforeach; ?>
<div class="panel" style="padding:18px;margin-bottom:16px"><h2 style="font-size:16px;margin:0 0 6px;color:var(--navy)">Xu&#7845;t v&#7853;t t&#432;</h2><p style="font-size:13px;color:#667085;margin:0 0 14px">Ch&#7881; xu&#7845;t cho phi&#7871;u &#273;&#227; duy&#7879;t, &#273;&#227; ph&#226;n c&#244;ng ho&#7863;c &#273;ang x&#7917; l&#253;. T&#7891;n kho s&#7869; gi&#7843;m ngay sau khi l&#432;u.</p><form method="post" action="/admin/warranties/<?= (int)$case['id'] ?>/materials" id="materialForm" style="display:grid;grid-template-columns:minmax(280px,2fr) 120px minmax(180px,1fr) auto;gap:12px;align-items:end"><?= csrfField() ?><div class="form-group" style="position:relative;margin:0"><label>V&#7853;t t&#432;/ph&#7909; t&#249;ng *</label><input id="materialSearch" autocomplete="off" placeholder="Nh&#7853;p t&#234;n, SKU ho&#7863;c m&#227; OEM" required><input type="hidden" name="product_id" id="materialProductId"><div id="materialSuggestions" style="display:none;position:absolute;z-index:10;left:0;right:0;top:100%;background:#fff;border:1px solid #d7deea;border-radius:6px;max-height:220px;overflow:auto"></div></div><div class="form-group" style="margin:0"><label>S&#7889; l&#432;&#7907;ng *</label><input name="quantity" type="number" min="1" max="1000" step="1" value="1" required></div><div class="form-group" style="margin:0"><label>Ghi ch&#250;</label><input name="note" maxlength="300" placeholder="L&#253; do/s&#7917; d&#7909;ng"></div><button class="btn btn-navy" type="submit">Xu&#7845;t v&#7853;t t&#432;</button></form></div>
<div class="panel"><div style="padding:14px 16px;border-bottom:1px solid var(--line);font-weight:700">L&#7883;ch s&#7917; v&#7853;t t&#432; &#273;&#227; xu&#7845;t (<?= count($materials) ?>)</div><div style="overflow:auto"><table class="tbl"><thead><tr><th>Th&#7901;i gian</th><th>V&#7853;t t&#432;</th><th>SKU / OEM</th><th>S&#7889; l&#432;&#7907;ng</th><th>Ghi ch&#250;</th><th>Ng&#432;&#7901;i xu&#7845;t</th></tr></thead><tbody><?php foreach($materials as $material): ?><tr><td><?= e($material['issued_at']) ?></td><td><?= e($material['product_name']) ?></td><td><?= e($material['sku']) ?><?= !empty($material['oem_code'])?' · '.e($material['oem_code']):'' ?></td><td><strong style="color:#b42318">-<?= (int)$material['quantity'] ?></strong></td><td><?= e($material['note']?:'—') ?></td><td><?= e($material['issued_by_name']?:'H&#7879; th&#7889;ng') ?></td></tr><?php endforeach; ?><?php if(!$materials): ?><tr><td colspan="6" style="text-align:center;padding:28px;color:#667085">Ch&#432;a xu&#7845;t v&#7853;t t&#432; cho phi&#7871;u n&#224;y.</td></tr><?php endif; ?></tbody></table></div></div>
<script>
(function(){var search=document.getElementById('materialSearch'),id=document.getElementById('materialProductId'),box=document.getElementById('materialSuggestions'),timer;function escapeHtml(value){var node=document.createElement('div');node.textContent=value;return node.innerHTML}search.addEventListener('input',function(){id.value='';clearTimeout(timer);var query=search.value.trim();box.style.display='none';if(query.length<2){return}timer=setTimeout(function(){fetch('/admin/warranties/material-products?q='+encodeURIComponent(query)).then(function(response){return response.json()}).then(function(items){box.innerHTML=items.map(function(item){return '<button type="button" data-id="'+item.id+'" data-label="'+escapeHtml(item.label)+'" style="display:block;width:100%;text-align:left;border:0;background:#fff;padding:9px 10px;cursor:pointer">'+escapeHtml(item.label)+'</button>'}).join('')||'<div style="padding:9px 10px;color:#667085">Kh\u00f4ng t\u00ecm th\u1ea5y v\u1eadt t\u01b0 c\u00f2n t\u1ed3n</div>';box.style.display='block'}).catch(function(){box.style.display='none'})},220)});box.addEventListener('click',function(event){var button=event.target.closest('button[data-id]');if(!button){return}id.value=button.dataset.id;search.value=button.dataset.label;box.style.display='none'});document.getElementById('materialForm').addEventListener('submit',function(event){if(!id.value){event.preventDefault();alert('H\u00e3y ch\u1ecdn v\u1eadt t\u01b0 t\u1eeb danh s\u00e1ch g\u1ee3i \u00fd.')}})})();
</script>
<?php require __DIR__ . '/../partials/dashboard-foot.php'; ?>
