import sys
from datetime import datetime
from pathlib import Path
import paramiko
sys.stdout.reconfigure(encoding='utf-8');ROOT=Path('cooling-php/_vps_live');APP='/opt/coolingsystems';DB='/var/lib/coolingsystems/cooling.db';c=paramiko.SSHClient();c.set_missing_host_key_policy(paramiko.AutoAddPolicy());c.connect('103.97.134.164',username='root',password='lcBFDjVF15',timeout=30)
def run(x):
 _,o,e=c.exec_command(x,timeout=90);a=o.read().decode('utf-8','replace');b=e.read().decode('utf-8','replace')
 if o.channel.recv_exit_status():raise RuntimeError(x+'\n'+a+b)
 return a.strip()
def rd(p):
 s=c.open_sftp();v=s.open(p,'rb').read().decode('utf-8');s.close();return v
def wr(p,v):
 s=c.open_sftp();f=s.open(p,'wb');f.write(v.encode('utf-8'));f.close();s.close()
stamp=datetime.now().strftime('%Y%m%d-%H%M%S');backup=f'/var/backups/coolingsystems/purchase-approval-po-phase69-{stamp}';routes_path=APP+'/routes/admin.php';view_path=APP+'/views/admin/purchase-requests.php';start="get('/admin/purchase-requests',function()";end="post('/admin/purchase-requests',function()"
get_route=r'''get('/admin/purchase-requests',function(){$u=requireStaffPermission('rbac:purchasing.requests.create|rbac:purchasing.requests.approve|rbac:purchasing.orders.create|tax_config','/admin/login');$suppliers=dbAll("SELECT id,code,name FROM suppliers WHERE is_active=1 ORDER BY name");$low=dbAll("SELECT id,sku,oem_code,name,stock,min_stock,max_stock FROM products WHERE status!='deleted' AND stock<=min_stock ORDER BY stock,min_stock,name LIMIT 500");$items=dbAll("SELECT pr.*,s.name AS supplier_name,u.full_name AS creator_name,COUNT(DISTINCT pri.id) AS item_count,po.code AS po_code FROM purchase_requests pr INNER JOIN suppliers s ON s.id=pr.supplier_id LEFT JOIN users u ON u.id=pr.created_by LEFT JOIN purchase_request_items pri ON pri.request_id=pr.id LEFT JOIN purchase_orders po ON po.source_request_id=pr.id GROUP BY pr.id ORDER BY CASE pr.status WHEN 'pending' THEN 0 WHEN 'approved' THEN 1 ELSE 2 END,pr.created_at DESC LIMIT 200");$canCreate=(($u['role']??'')==='admin')||rbacHasCapability((int)$u['id'],'purchasing.requests.create');$canApprove=(($u['role']??'')==='admin')||rbacHasCapability((int)$u['id'],'purchasing.requests.approve');$canCreateOrder=(($u['role']??'')==='admin')||rbacHasCapability((int)$u['id'],'purchasing.orders.create');view('admin/purchase-requests',['title'=>'Yêu cầu mua hàng','userRole'=>'admin','suppliers'=>$suppliers,'low'=>$low,'items'=>$items,'canCreate'=>$canCreate,'canApprove'=>$canApprove,'canCreateOrder'=>$canCreateOrder,'currentUserId'=>(int)$u['id']]);});
'''
extra=r'''post('/admin/purchase-requests/:id/approve',function($p){$u=requireStaffPermission('rbac:purchasing.requests.approve|tax_config','/admin/login');csrfCheck();$r=dbGet("SELECT * FROM purchase_requests WHERE id=?",[$p['id']]);if(!$r||$r['status']!=='pending'||(int)$r['created_by']===(int)$u['id']){flash('error','Không thể duyệt yêu cầu mua này.');redirect('/admin/purchase-requests');}dbRun("UPDATE purchase_requests SET status='approved',approved_by=?,approved_at=datetime('now','localtime') WHERE id=? AND status='pending'",[$u['id'],$r['id']]);dbRun("INSERT INTO audit_logs (user_id,role,action,entity_type,entity_id,meta,ip,user_agent) VALUES (?,?,?,?,?,?,?,?)",[$u['id'],$u['role']??'admin','purchase_request_approved','purchase_request',$r['id'],'{}',$_SERVER['REMOTE_ADDR']??'',$_SERVER['HTTP_USER_AGENT']??'']);flash('success','Đã duyệt yêu cầu mua.');redirect('/admin/purchase-requests');});
post('/admin/purchase-requests/:id/reject',function($p){$u=requireStaffPermission('rbac:purchasing.requests.approve|tax_config','/admin/login');csrfCheck();$reason=trim($_POST['reason']??'');$r=dbGet("SELECT * FROM purchase_requests WHERE id=?",[$p['id']]);if(!$r||$r['status']!=='pending'||(int)$r['created_by']===(int)$u['id']||mb_strlen($reason)<5||mb_strlen($reason)>300){flash('error','Cần lý do từ chối 5-300 ký tự và người duyệt phải khác người lập.');redirect('/admin/purchase-requests');}dbRun("UPDATE purchase_requests SET status='rejected',approved_by=?,approved_at=datetime('now','localtime'),rejection_reason=? WHERE id=? AND status='pending'",[$u['id'],$reason,$r['id']]);flash('success','Đã từ chối yêu cầu mua.');redirect('/admin/purchase-requests');});
post('/admin/purchase-requests/:id/purchase-order',function($p){$u=requireStaffPermission('rbac:purchasing.orders.create|tax_config','/admin/login');csrfCheck();$pdo=db();try{$pdo->beginTransaction();$r=dbGet("SELECT * FROM purchase_requests WHERE id=?",[$p['id']]);if(!$r||$r['status']!=='approved'||dbGet('SELECT id FROM purchase_orders WHERE source_request_id=?',[$r['id']]))throw new RuntimeException('invalid');$lines=dbAll("SELECT pri.*,COALESCE(p.cost_price,0) AS unit_cost FROM purchase_request_items pri INNER JOIN products p ON p.id=pri.product_id WHERE pri.request_id=?",[$r['id']]);if(!$lines)throw new RuntimeException('invalid');$total=0;foreach($lines as $line)$total+=(int)$line['requested_qty']*(int)$line['unit_cost'];$code='PO-'.date('Ymd-His').'-'.str_pad((string)$r['id'],5,'0',STR_PAD_LEFT);$oid=dbInsert("INSERT INTO purchase_orders (code,source_request_id,supplier_id,status,total_amount,created_by) VALUES (?,?,?,'draft',?,?)",[$code,$r['id'],$r['supplier_id'],$total,$u['id']]);foreach($lines as $line)dbInsert('INSERT INTO purchase_order_items (order_id,product_id,sku,product_name,ordered_qty,unit_cost,line_total) VALUES (?,?,?,?,?,?,?)',[$oid,$line['product_id'],$line['sku'],$line['product_name'],$line['requested_qty'],$line['unit_cost'],(int)$line['requested_qty']*(int)$line['unit_cost']]);dbRun("INSERT INTO audit_logs (user_id,role,action,entity_type,entity_id,meta,ip,user_agent) VALUES (?,?,?,?,?,?,?,?)",[$u['id'],$u['role']??'admin','purchase_order_created','purchase_order',$oid,json_encode(['code'=>$code,'request_id'=>$r['id']],JSON_UNESCAPED_UNICODE),$_SERVER['REMOTE_ADDR']??'',$_SERVER['HTTP_USER_AGENT']??'']);$pdo->commit();flash('success','Đã tạo PO '.$code.' ở trạng thái nháp.');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('error','Không thể tạo PO từ yêu cầu này.');}redirect('/admin/purchase-requests');});
'''
try:
 run(f"mkdir -p {backup} && sqlite3 {DB} \".backup '{backup}/cooling.db'\" && cp {routes_path} {backup}/admin.php && cp {view_path} {backup}/purchase-requests.php")
 if run(f"sqlite3 {DB} \"SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='purchase_orders';\"")!='0':raise RuntimeError('PO table already exists')
 routes=rd(routes_path);a=routes.find(start);b=routes.find(end,a)
 if a<0 or b<0 or 'purchase_request_approved' in routes:raise RuntimeError('route markers invalid')
 routes=routes[:a]+get_route+routes[b:];marker="get('/admin/warranties', function() {";routes=routes.replace(marker,extra+marker,1);wr('/tmp/p69-r.php',routes);s=c.open_sftp();s.put(str(ROOT/'purchase-requests_phase69.php'),'/tmp/p69-v.php');s.close();seed="<?php $p=new PDO('sqlite:"+DB+"');$q=$p->prepare('INSERT OR REPLACE INTO rbac_capability_rules (capability,permission_code,allowed_levels) VALUES (?,?,?)');$q->execute(['purchasing.requests.approve','P81',json_encode(['TQ','QL'])]);$q->execute(['purchasing.orders.create','P82',json_encode(['TQ','QL','TH'])]);";wr('/tmp/p69-seed.php',seed)
 schema="ALTER TABLE purchase_requests ADD COLUMN approved_by INTEGER;ALTER TABLE purchase_requests ADD COLUMN approved_at TEXT;ALTER TABLE purchase_requests ADD COLUMN rejection_reason TEXT;CREATE TABLE purchase_orders (id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT NOT NULL UNIQUE,source_request_id INTEGER NOT NULL UNIQUE,supplier_id INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'draft',total_amount INTEGER NOT NULL DEFAULT 0,created_by INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT (datetime('now','localtime')));CREATE TABLE purchase_order_items (id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER NOT NULL,product_id INTEGER NOT NULL,sku TEXT,product_name TEXT,ordered_qty INTEGER NOT NULL,unit_cost INTEGER NOT NULL DEFAULT 0,line_total INTEGER NOT NULL DEFAULT 0);"
 out=run("chown www-data:www-data /tmp/p69-* && runuser -u www-data -- php /tmp/p69-seed.php && "+f"sqlite3 {DB} \"{schema}\" && install -o www-data -g www-data -m 0644 /tmp/p69-r.php {routes_path} && install -o www-data -g www-data -m 0644 /tmp/p69-v.php {view_path} && php -l {routes_path} && php -l {view_path} && rm -f /tmp/p69-*")
 print('BACKUP='+backup);print('LINT='+out);print('HOME='+run("curl -s -o /dev/null -w '%{http_code}' https://coolingsystems.vn/"));print('RBAC='+run(f"sqlite3 -separator '|' {DB} \"SELECT capability,permission_code FROM rbac_capability_rules WHERE permission_code IN ('P81','P82') ORDER BY permission_code;\""))
except Exception:
 run(f"test -f {backup}/cooling.db && sqlite3 {DB} \".restore '{backup}/cooling.db'\";test -f {backup}/admin.php && cp {backup}/admin.php {routes_path};test -f {backup}/purchase-requests.php && cp {backup}/purchase-requests.php {view_path};rm -f /tmp/p69-*;chown www-data:www-data {DB} {routes_path} {view_path}");c.close();raise
c.close()
