import sys
from datetime import datetime
import paramiko
sys.stdout.reconfigure(encoding='utf-8');A='/opt/coolingsystems';D='/var/lib/coolingsystems/cooling.db';c=paramiko.SSHClient();c.set_missing_host_key_policy(paramiko.AutoAddPolicy());c.connect('103.97.134.164',username='root',password='lcBFDjVF15',timeout=30)
def run(x):
 _,o,e=c.exec_command(x,timeout=90);a=o.read().decode('utf-8','replace');b=e.read().decode('utf-8','replace')
 if o.channel.recv_exit_status():raise RuntimeError(x+'\n'+a+b)
 return a.strip()
def rd(p):
 s=c.open_sftp();v=s.open(p,'rb').read().decode();s.close();return v
def wr(p,v):
 s=c.open_sftp();s.open(p,'wb').write(v.encode());s.close()
s=datetime.now().strftime('%Y%m%d-%H%M%S');B=f'/var/backups/coolingsystems/purchase-requests-phase68-{s}';rp=A+'/routes/admin.php';hp=A+'/views/partials/dashboard-head.php';vp=A+'/views/admin/purchase-requests.php';m="get('/admin/warranties', function() {"
routes=r'''get('/admin/purchase-requests',function(){$u=requireStaffPermission('rbac:purchasing.requests.create|tax_config','/admin/login');$suppliers=dbAll("SELECT id,code,name FROM suppliers WHERE is_active=1 ORDER BY name");$low=dbAll("SELECT id,sku,oem_code,name,stock,min_stock,max_stock FROM products WHERE status!='deleted' AND stock<=min_stock ORDER BY stock,min_stock,name LIMIT 500");$items=dbAll("SELECT pr.*,s.name AS supplier_name,COUNT(pri.id) AS item_count FROM purchase_requests pr INNER JOIN suppliers s ON s.id=pr.supplier_id LEFT JOIN purchase_request_items pri ON pri.request_id=pr.id GROUP BY pr.id ORDER BY pr.created_at DESC LIMIT 200");$can=(($u['role']??'')==='admin')||rbacHasCapability((int)$u['id'],'purchasing.requests.create');view('admin/purchase-requests',['title'=>'Yêu cầu mua hàng','userRole'=>'admin','suppliers'=>$suppliers,'low'=>$low,'items'=>$items,'canCreate'=>$can]);});
post('/admin/purchase-requests',function(){$u=requireStaffPermission('rbac:purchasing.requests.create|tax_config','/admin/login');csrfCheck();$sid=(int)($_POST['supplier_id']??0);$note=trim($_POST['note']??'');$qty=$_POST['qty']??[];if(!$sid||mb_strlen($note)>500||!is_array($qty)){flash('error','Dữ liệu yêu cầu mua không hợp lệ.');redirect('/admin/purchase-requests');}$supplier=dbGet('SELECT id FROM suppliers WHERE id=? AND is_active=1',[$sid]);if(!$supplier){flash('error','Nhà cung cấp không hợp lệ.');redirect('/admin/purchase-requests');}$lines=[];foreach($qty as $id=>$n){$id=(int)$id;$n=(int)preg_replace('/\D/','',(string)$n);if($n>0&&$n<=100000){$p=dbGet("SELECT id,sku,name,stock,min_stock,max_stock FROM products WHERE id=? AND status!='deleted'",[$id]);if($p)$lines[]=[$p,$n];}}if(!$lines){flash('error','Hãy nhập số lượng mua cho ít nhất một sản phẩm.');redirect('/admin/purchase-requests');}$pdo=db();try{$pdo->beginTransaction();$code='YCM-'.date('Ymd-His').'-'.random_int(100,999);$rid=dbInsert("INSERT INTO purchase_requests (code,supplier_id,status,note,created_by) VALUES (?,?,'pending',?,?)",[$code,$sid,$note,$u['id']??null]);foreach($lines as [$p,$n])dbInsert('INSERT INTO purchase_request_items (request_id,product_id,sku,product_name,current_stock,min_stock,requested_qty) VALUES (?,?,?,?,?,?,?)',[$rid,$p['id'],$p['sku'],$p['name'],$p['stock'],$p['min_stock'],$n]);dbRun("INSERT INTO audit_logs (user_id,role,action,entity_type,entity_id,meta,ip,user_agent) VALUES (?,?,?,?,?,?,?,?)",[$u['id']??null,$u['role']??'admin','purchase_request_created','purchase_request',$rid,json_encode(['code'=>$code,'lines'=>count($lines)],JSON_UNESCAPED_UNICODE),$_SERVER['REMOTE_ADDR']??'',$_SERVER['HTTP_USER_AGENT']??'']);$pdo->commit();flash('success','Đã tạo yêu cầu mua '.$code.' chờ duyệt.');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('error','Không thể tạo yêu cầu mua.');}redirect('/admin/purchase-requests');});
'''
view='''<?php require __DIR__.'/../partials/dashboard-head.php';?><div class="dash-head"><h1>Yêu cầu mua hàng</h1><p style="color:#667085">Tạo yêu cầu mua từ sản phẩm chạm tồn tối thiểu.</p></div><?php foreach(getFlash() as $x):?><div class="alert alert-<?=e($x['type'])?>"><?=e($x['message'])?></div><?php endforeach;?><?php if($canCreate):?><div class="panel" style="padding:16px;margin-bottom:16px"><form method="post" action="/admin/purchase-requests"><?=csrfField()?><div style="display:flex;gap:12px;align-items:end;flex-wrap:wrap"><div class="form-group" style="min-width:280px"><label>Nhà cung cấp *</label><select name="supplier_id" required><option value="">Chọn nhà cung cấp</option><?php foreach($suppliers as $s):?><option value="<?=$s['id']?>"><?=e($s['name'])?></option><?php endforeach;?></select></div><div class="form-group" style="flex:1;min-width:280px"><label>Ghi chú</label><input name="note" maxlength="500"></div><button class="btn btn-navy">Tạo yêu cầu mua</button></div><div style="overflow:auto;margin-top:14px"><table class="tbl"><thead><tr><th>Sản phẩm</th><th>Tồn</th><th>Tối thiểu</th><th>Đề nghị mua</th></tr></thead><tbody><?php foreach($low as $p):?><tr><td><strong><?=e($p['name'])?></strong><div class="fs-11 text-muted"><?=e($p['sku'])?> <?=e($p['oem_code'])?></div></td><td><?=$p['stock']?></td><td><?=$p['min_stock']?></td><td><input name="qty[<?=$p['id']?>]" inputmode="numeric" value="<?=max(1,$p['max_stock']-$p['stock'])?>" style="width:110px"></td></tr><?php endforeach;?><?php if(!$low):?><tr><td colspan="4" style="padding:24px;text-align:center">Không có sản phẩm chạm tồn tối thiểu.</td></tr><?php endif;?></tbody></table></div></form></div><?php endif;?><div class="panel"><table class="tbl"><thead><tr><th>Mã</th><th>Nhà cung cấp</th><th>Số mặt hàng</th><th>Trạng thái</th><th>Ngày tạo</th></tr></thead><tbody><?php foreach($items as $i):?><tr><td><?=e($i['code'])?></td><td><?=e($i['supplier_name'])?></td><td><?=$i['item_count']?></td><td>Chờ duyệt</td><td><?=e($i['created_at'])?></td></tr><?php endforeach;?></tbody></table></div><?php require __DIR__.'/../partials/dashboard-foot.php';?>'''
try:
 run(f"mkdir -p {B} && sqlite3 {D} \".backup '{B}/cooling.db'\" && cp {rp} {B}/admin.php && cp {hp} {B}/head.php")
 if run(f"sqlite3 {D} \"SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='purchase_requests';\"")!='0':raise RuntimeError('purchase table exists')
 r=rd(rp);wr('/tmp/pr-r.php',r.replace(m,routes+m,1));h=rd(hp);old='<a href="/admin/suppliers" class="<?= startsWith(currentPath(),\'/admin/suppliers\')?\'active\':\'\' ?>"><?= sbIcon(\'list\') ?>Nh&#224; cung c&#7845;p</a>';new=old+'<?php if($__isAdmin || ($__sbU && function_exists(\'rbacCan\') && rbacCan((int)$__sbU[\'id\'],\'purchasing.requests.create\'))): ?><a href="/admin/purchase-requests" class="<?= startsWith(currentPath(),\'/admin/purchase-requests\')?\'active\':\'\' ?>"><?= sbIcon(\'list\') ?>Y&#234;u c&#7847;u mua</a><?php endif; ?>';wr('/tmp/pr-h.php',h.replace(old,new,1));wr('/tmp/pr-v.php',view);wr('/tmp/pr-seed.php',"<?php $p=new PDO('sqlite:"+D+"');$p->prepare('INSERT OR REPLACE INTO rbac_capability_rules (capability,permission_code,allowed_levels) VALUES (?,?,?)')->execute(['purchasing.requests.create','P80',json_encode(['TQ','QL','TH'])]);")
 schema="CREATE TABLE purchase_requests (id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT NOT NULL UNIQUE,supplier_id INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'pending',note TEXT,created_by INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT (datetime('now','localtime')),FOREIGN KEY(supplier_id) REFERENCES suppliers(id));CREATE TABLE purchase_request_items (id INTEGER PRIMARY KEY AUTOINCREMENT,request_id INTEGER NOT NULL,product_id INTEGER NOT NULL,sku TEXT,product_name TEXT,current_stock INTEGER,min_stock INTEGER,requested_qty INTEGER NOT NULL,FOREIGN KEY(request_id) REFERENCES purchase_requests(id));"
 o=run("chown www-data:www-data /tmp/pr-* && runuser -u www-data -- php /tmp/pr-seed.php && "+f"sqlite3 {D} \"{schema}\" && install -o www-data -g www-data -m 0644 /tmp/pr-r.php {rp} && install -o www-data -g www-data -m 0644 /tmp/pr-h.php {hp} && install -o www-data -g www-data -m 0644 /tmp/pr-v.php {vp} && php -l {rp} && php -l {hp} && php -l {vp} && rm -f /tmp/pr-*")
 print('BACKUP='+B);print('LINT='+o);print('HOME='+run("curl -s -o /dev/null -w '%{http_code}' https://coolingsystems.vn/"));print('P80='+run(f"sqlite3 -separator '|' {D} \"SELECT capability,permission_code FROM rbac_capability_rules WHERE capability='purchasing.requests.create';\""))
except Exception:
 run(f"test -f {B}/cooling.db && sqlite3 {D} \".restore '{B}/cooling.db'\";test -f {B}/admin.php && cp {B}/admin.php {rp};test -f {B}/head.php && cp {B}/head.php {hp};rm -f {vp} /tmp/pr-*;chown www-data:www-data {D} {rp} {hp}");c.close();raise
c.close()
