import sys
from datetime import datetime
from pathlib import Path
import paramiko
sys.stdout.reconfigure(encoding='utf-8');ROOT=Path('cooling-php/_vps_live');APP='/opt/coolingsystems';DB='/var/lib/coolingsystems/cooling.db';c=paramiko.SSHClient();c.set_missing_host_key_policy(paramiko.AutoAddPolicy());c.connect('103.97.134.164',username='root',password='lcBFDjVF15',timeout=30)
def run(x):
 _,o,e=c.exec_command(x,timeout=90);a=o.read().decode('utf-8','replace');b=e.read().decode('utf-8','replace')
 if o.channel.recv_exit_status():raise RuntimeError(x+'\n'+a+b)
 return a.strip()
def rd(p):
 s=c.open_sftp();f=s.open(p,'rb');v=f.read().decode('utf-8');f.close();s.close();return v
def wr(p,v):
 s=c.open_sftp();f=s.open(p,'wb');f.write(v.encode('utf-8'));f.close();s.close()
stamp=datetime.now().strftime('%Y%m%d-%H%M%S');B=f'/var/backups/coolingsystems/supplier-returns-phase74-{stamp}';rp=APP+'/routes/admin.php';hp=APP+'/views/partials/dashboard-head.php';vp=APP+'/views/admin/supplier-returns.php';marker="get('/admin/warranties', function() {"
routes=r'''get('/admin/supplier-returns',function(){$u=requireStaffPermission('rbac:purchasing.returns.create|tax_config','/admin/login');$receipts=dbAll("SELECT gr.id,gr.code,po.code AS po_code,s.name AS supplier_name FROM goods_receipts gr INNER JOIN purchase_orders po ON po.id=gr.order_id INNER JOIN suppliers s ON s.id=po.supplier_id WHERE gr.status='qc_completed' ORDER BY gr.qc_at DESC");$selectedReceipt=max(0,(int)($_GET['receipt']??0));$receipt=$selectedReceipt?dbGet("SELECT gr.*,po.code AS po_code,s.name AS supplier_name FROM goods_receipts gr INNER JOIN purchase_orders po ON po.id=gr.order_id INNER JOIN suppliers s ON s.id=po.supplier_id WHERE gr.id=? AND gr.status='qc_completed'",[$selectedReceipt]):null;$lines=$receipt?dbAll("SELECT gri.*,p.name AS product_name,p.sku,COALESCE((SELECT SUM(sri.return_qty) FROM supplier_return_items sri INNER JOIN supplier_returns sr ON sr.id=sri.return_id WHERE sri.receipt_item_id=gri.id AND sr.status!='rejected'),0) AS returned_qty FROM goods_receipt_items gri INNER JOIN products p ON p.id=gri.product_id WHERE gri.receipt_id=? ORDER BY gri.id",[$selectedReceipt]):[];$items=dbAll("SELECT sr.*,gr.code AS receipt_code,s.name AS supplier_name,COALESCE(SUM(sri.return_qty),0) AS total_qty FROM supplier_returns sr INNER JOIN goods_receipts gr ON gr.id=sr.receipt_id INNER JOIN purchase_orders po ON po.id=gr.order_id INNER JOIN suppliers s ON s.id=po.supplier_id LEFT JOIN supplier_return_items sri ON sri.return_id=sr.id GROUP BY sr.id ORDER BY sr.created_at DESC LIMIT 200");view('admin/supplier-returns',['title'=>'Trả hàng nhà cung cấp','userRole'=>'admin','receipts'=>$receipts,'selectedReceipt'=>$selectedReceipt,'receipt'=>$receipt,'lines'=>$lines,'items'=>$items]);});
post('/admin/supplier-returns',function(){$u=requireStaffPermission('rbac:purchasing.returns.create|tax_config','/admin/login');csrfCheck();$rid=(int)($_POST['receipt_id']??0);$reason=trim($_POST['reason']??'');$qty=$_POST['qty']??[];if(!$rid||mb_strlen($reason)<5||mb_strlen($reason)>500||!is_array($qty)){flash('error','Lý do trả phải từ 5-500 ký tự.');redirect('/admin/supplier-returns?receipt='.$rid);}$pdo=db();try{$pdo->beginTransaction();$receipt=dbGet("SELECT * FROM goods_receipts WHERE id=? AND status='qc_completed'",[$rid]);if(!$receipt)throw new RuntimeException('receipt');$lines=[];foreach($qty as $id=>$raw){$id=(int)$id;$n=(int)preg_replace('/\D/','',(string)$raw);if($n<1)continue;$line=dbGet("SELECT gri.*,COALESCE((SELECT SUM(sri.returned_rejected_qty) FROM supplier_return_items sri INNER JOIN supplier_returns sr ON sr.id=sri.return_id WHERE sri.receipt_item_id=gri.id AND sr.status!='rejected'),0) AS used_bad,COALESCE((SELECT SUM(sri.returned_accepted_qty) FROM supplier_return_items sri INNER JOIN supplier_returns sr ON sr.id=sri.return_id WHERE sri.receipt_item_id=gri.id AND sr.status!='rejected'),0) AS used_good FROM goods_receipt_items gri WHERE gri.id=? AND gri.receipt_id=?",[$id,$rid]);if(!$line)throw new RuntimeException('qty');$badAvail=max(0,(int)$line['rejected_qty']-(int)$line['used_bad']);$goodAvail=max(0,(int)$line['accepted_qty']-(int)$line['used_good']);if($n>$badAvail+$goodAvail)throw new RuntimeException('qty');$bad=min($n,$badAvail);$good=$n-$bad;$lines[]=[$line,$n,$good,$bad];}if(!$lines)throw new RuntimeException('qty');$code='THNCC-'.date('Ymd-His').'-'.random_int(100,999);$returnId=dbInsert("INSERT INTO supplier_returns (code,receipt_id,status,reason,created_by) VALUES (?,?,'pending',?,?)",[$code,$rid,$reason,$u['id']]);foreach($lines as [$line,$n,$good,$bad])dbInsert('INSERT INTO supplier_return_items (return_id,receipt_item_id,product_id,return_qty,returned_accepted_qty,returned_rejected_qty) VALUES (?,?,?,?,?,?)',[$returnId,$line['id'],$line['product_id'],$n,$good,$bad]);dbRun("INSERT INTO audit_logs (user_id,role,action,entity_type,entity_id,meta,ip,user_agent) VALUES (?,?,?,?,?,?,?,?)",[$u['id'],$u['role']??'admin','supplier_return_created','supplier_return',$returnId,json_encode(['receipt_id'=>$rid,'lines'=>count($lines)],JSON_UNESCAPED_UNICODE),$_SERVER['REMOTE_ADDR']??'',$_SERVER['HTTP_USER_AGENT']??'']);$pdo->commit();flash('success','Đã tạo phiếu trả '.$code.' chờ duyệt.');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('error',$e->getMessage()==='qty'?'Số lượng trả vượt quá số lượng còn có thể trả.':'Không thể tạo phiếu trả nhà cung cấp.');}redirect('/admin/supplier-returns');});
'''
try:
 run(f"mkdir -p {B} && sqlite3 {DB} \".backup '{B}/cooling.db'\" && cp {rp} {B}/admin.php && cp {hp} {B}/head.php")
 if run(f"sqlite3 {DB} \"SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='supplier_returns';\"")!='0':raise RuntimeError('P87 table exists')
 r=rd(rp)
 if r.count(marker)!=1 or 'supplier_return_created' in r:raise RuntimeError('route marker')
 wr('/tmp/p74-r.php',r.replace(marker,routes+marker,1));h=rd(hp);old='<a href="/admin/purchase-costs" class="<?= startsWith(currentPath(),\'/admin/purchase-costs\')?\'active\':\'\' ?>"><?= sbIcon(\'list\') ?>Chi ph&#237; mua</a>';new=old+'<?php if($__isAdmin || ($__sbU && function_exists(\'rbacCan\') && rbacCan((int)$__sbU[\'id\'],\'purchasing.returns.create\'))): ?><a href="/admin/supplier-returns" class="<?= startsWith(currentPath(),\'/admin/supplier-returns\')?\'active\':\'\' ?>"><?= sbIcon(\'list\') ?>Tr&#7843; h&#224;ng NCC</a><?php endif; ?>'
 if h.count(old)!=1:raise RuntimeError('menu marker')
 wr('/tmp/p74-h.php',h.replace(old,new,1));s=c.open_sftp();s.put(str(ROOT/'supplier-returns_phase74.php'),'/tmp/p74-v.php');s.close();wr('/tmp/p74-seed.php',"<?php $p=new PDO('sqlite:"+DB+"');$p->prepare('INSERT OR REPLACE INTO rbac_capability_rules (capability,permission_code,allowed_levels) VALUES (?,?,?)')->execute(['purchasing.returns.create','P87',json_encode(['TQ','QL','TH'])]);")
 schema="CREATE TABLE supplier_returns (id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT NOT NULL UNIQUE,receipt_id INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'pending',reason TEXT NOT NULL,created_by INTEGER NOT NULL,approved_by INTEGER,approved_at TEXT,rejection_reason TEXT,created_at TEXT NOT NULL DEFAULT (datetime('now','localtime')));CREATE TABLE supplier_return_items (id INTEGER PRIMARY KEY AUTOINCREMENT,return_id INTEGER NOT NULL,receipt_item_id INTEGER NOT NULL,product_id INTEGER NOT NULL,return_qty INTEGER NOT NULL,returned_accepted_qty INTEGER NOT NULL DEFAULT 0,returned_rejected_qty INTEGER NOT NULL DEFAULT 0);"
 o=run("chown www-data:www-data /tmp/p74-* && runuser -u www-data -- php /tmp/p74-seed.php && "+f"sqlite3 {DB} \"{schema}\" && install -o www-data -g www-data -m 0644 /tmp/p74-r.php {rp} && install -o www-data -g www-data -m 0644 /tmp/p74-h.php {hp} && install -o www-data -g www-data -m 0644 /tmp/p74-v.php {vp} && php -l {rp} && php -l {hp} && php -l {vp} && rm -f /tmp/p74-*")
 print('BACKUP='+B);print('LINT='+o);print('HOME='+run("curl -s -o /dev/null -w '%{http_code}' https://coolingsystems.vn/"));print('P87='+run(f"sqlite3 -separator '|' {DB} \"SELECT capability,permission_code FROM rbac_capability_rules WHERE permission_code='P87';\""))
except Exception:
 run(f"test -f {B}/cooling.db && sqlite3 {DB} \".restore '{B}/cooling.db'\";test -f {B}/admin.php && cp {B}/admin.php {rp};test -f {B}/head.php && cp {B}/head.php {hp};rm -f {vp} /tmp/p74-*;chown www-data:www-data {DB} {rp} {hp}");c.close();raise
c.close()
