import sys
from datetime import datetime
from pathlib import Path
import paramiko
sys.stdout.reconfigure(encoding='utf-8');ROOT=Path('cooling-php/_vps_live');APP='/opt/coolingsystems';DB='/var/lib/coolingsystems/cooling.db';c=paramiko.SSHClient();c.set_missing_host_key_policy(paramiko.AutoAddPolicy());c.connect('103.97.134.164',username='root',password='lcBFDjVF15',timeout=30)
def run(x):
 _,o,e=c.exec_command(x,timeout=90);a=o.read().decode('utf-8','replace');b=e.read().decode('utf-8','replace')
 if o.channel.recv_exit_status():raise RuntimeError(x+'\n'+a+b)
 return a.strip()
def rd(p):
 s=c.open_sftp();f=s.open(p,'rb');v=f.read().decode('utf-8');f.close();s.close();return v
def wr(p,v):
 s=c.open_sftp();f=s.open(p,'wb');f.write(v.encode('utf-8'));f.close();s.close()
stamp=datetime.now().strftime('%Y%m%d-%H%M%S');B=f'/var/backups/coolingsystems/purchase-costs-phase73-{stamp}';rp=APP+'/routes/admin.php';hp=APP+'/views/partials/dashboard-head.php';vp=APP+'/views/admin/purchase-costs.php';marker="get('/admin/warranties', function() {"
routes=r'''get('/admin/purchase-costs',function(){$u=requireStaffPermission('rbac:purchasing.costs.allocate|tax_config','/admin/login');$receipts=dbAll("SELECT gr.id,gr.code,po.code AS po_code,s.name AS supplier_name FROM goods_receipts gr INNER JOIN purchase_orders po ON po.id=gr.order_id INNER JOIN suppliers s ON s.id=po.supplier_id LEFT JOIN purchase_cost_allocations pca ON pca.receipt_id=gr.id WHERE gr.status='qc_completed' AND pca.id IS NULL AND EXISTS(SELECT 1 FROM goods_receipt_items gri WHERE gri.receipt_id=gr.id AND gri.accepted_qty>0) ORDER BY gr.qc_at");$items=dbAll("SELECT pca.*,gr.code AS receipt_code,po.code AS po_code,s.name AS supplier_name FROM purchase_cost_allocations pca INNER JOIN goods_receipts gr ON gr.id=pca.receipt_id INNER JOIN purchase_orders po ON po.id=gr.order_id INNER JOIN suppliers s ON s.id=po.supplier_id ORDER BY pca.created_at DESC LIMIT 200");view('admin/purchase-costs',['title'=>'Phân bổ chi phí mua','userRole'=>'admin','receipts'=>$receipts,'items'=>$items]);});
post('/admin/purchase-costs',function(){$u=requireStaffPermission('rbac:purchasing.costs.allocate|tax_config','/admin/login');csrfCheck();$rid=(int)($_POST['receipt_id']??0);$shipping=(int)preg_replace('/\D/','',$_POST['shipping_cost']??'0');$tax=(int)preg_replace('/\D/','',$_POST['tax_cost']??'0');$other=(int)preg_replace('/\D/','',$_POST['other_cost']??'0');$note=trim($_POST['note']??'');$total=$shipping+$tax+$other;if(!$rid||$total<1||$total>999999999999||mb_strlen($note)>500){flash('error','Dữ liệu chi phí mua không hợp lệ.');redirect('/admin/purchase-costs');}$pdo=db();try{$pdo->beginTransaction();$receipt=dbGet("SELECT * FROM goods_receipts WHERE id=? AND status='qc_completed'",[$rid]);if(!$receipt||dbGet('SELECT id FROM purchase_cost_allocations WHERE receipt_id=?',[$rid]))throw new RuntimeException('receipt');$lines=dbAll("SELECT gri.id,gri.product_id,gri.accepted_qty,poi.unit_cost FROM goods_receipt_items gri INNER JOIN purchase_order_items poi ON poi.id=gri.order_item_id WHERE gri.receipt_id=? AND gri.accepted_qty>0 ORDER BY gri.id",[$rid]);if(!$lines)throw new RuntimeException('receipt');$weight=0;foreach($lines as $line)$weight+=(int)$line['accepted_qty']*max(0,(int)$line['unit_cost']);$useQty=$weight===0;if($useQty){foreach($lines as $line)$weight+=(int)$line['accepted_qty'];}$code='CPM-'.date('Ymd-His').'-'.random_int(100,999);$aid=dbInsert('INSERT INTO purchase_cost_allocations (code,receipt_id,shipping_cost,tax_cost,other_cost,total_cost,note,created_by) VALUES (?,?,?,?,?,?,?,?)',[$code,$rid,$shipping,$tax,$other,$total,$note,$u['id']]);$allocated=0;$last=count($lines)-1;foreach($lines as $index=>$line){$lineWeight=$useQty?(int)$line['accepted_qty']:(int)$line['accepted_qty']*(int)$line['unit_cost'];$amount=$index===$last?$total-$allocated:(int)floor($total*$lineWeight/$weight);$allocated+=$amount;dbInsert('INSERT INTO purchase_cost_allocation_items (allocation_id,receipt_item_id,product_id,allocated_cost) VALUES (?,?,?,?)',[$aid,$line['id'],$line['product_id'],$amount]);dbRun("UPDATE products SET total_import_value=total_import_value+?,cost_price=CASE WHEN stock>0 THEN ROUND((total_import_value+?)*1.0/stock) ELSE cost_price END,updated_at=datetime('now','localtime') WHERE id=?",[$amount,$amount,$line['product_id']]);}dbRun("INSERT INTO audit_logs (user_id,role,action,entity_type,entity_id,meta,ip,user_agent) VALUES (?,?,?,?,?,?,?,?)",[$u['id'],$u['role']??'admin','purchase_cost_allocated','goods_receipt',$rid,json_encode(['allocation_id'=>$aid,'total'=>$total],JSON_UNESCAPED_UNICODE),$_SERVER['REMOTE_ADDR']??'',$_SERVER['HTTP_USER_AGENT']??'']);$pdo->commit();flash('success','Đã phân bổ '.$total.' đ vào giá vốn.');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('error','Phiếu không hợp lệ hoặc đã được phân bổ chi phí.');}redirect('/admin/purchase-costs');});
'''
try:
 run(f"mkdir -p {B} && sqlite3 {DB} \".backup '{B}/cooling.db'\" && cp {rp} {B}/admin.php && cp {hp} {B}/head.php")
 if run(f"sqlite3 {DB} \"SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='purchase_cost_allocations';\"")!='0':raise RuntimeError('P86 table exists')
 r=rd(rp)
 if r.count(marker)!=1 or 'purchase_cost_allocated' in r:raise RuntimeError('route marker')
 wr('/tmp/p73-r.php',r.replace(marker,routes+marker,1));h=rd(hp);old='<a href="/admin/purchase-quality" class="<?= startsWith(currentPath(),\'/admin/purchase-quality\')?\'active\':\'\' ?>"><?= sbIcon(\'list\') ?>Ki&#7875;m ch&#7845;t l&#432;&#7907;ng</a>';new=old+'<?php if($__isAdmin || ($__sbU && function_exists(\'rbacCan\') && rbacCan((int)$__sbU[\'id\'],\'purchasing.costs.allocate\'))): ?><a href="/admin/purchase-costs" class="<?= startsWith(currentPath(),\'/admin/purchase-costs\')?\'active\':\'\' ?>"><?= sbIcon(\'list\') ?>Chi ph&#237; mua</a><?php endif; ?>'
 if h.count(old)!=1:raise RuntimeError('menu marker')
 wr('/tmp/p73-h.php',h.replace(old,new,1));s=c.open_sftp();s.put(str(ROOT/'purchase-costs_phase73.php'),'/tmp/p73-v.php');s.close();wr('/tmp/p73-seed.php',"<?php $p=new PDO('sqlite:"+DB+"');$p->prepare('INSERT OR REPLACE INTO rbac_capability_rules (capability,permission_code,allowed_levels) VALUES (?,?,?)')->execute(['purchasing.costs.allocate','P86',json_encode(['TQ','QL'])]);")
 schema="CREATE TABLE purchase_cost_allocations (id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT NOT NULL UNIQUE,receipt_id INTEGER NOT NULL UNIQUE,shipping_cost INTEGER NOT NULL DEFAULT 0,tax_cost INTEGER NOT NULL DEFAULT 0,other_cost INTEGER NOT NULL DEFAULT 0,total_cost INTEGER NOT NULL,note TEXT,created_by INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT (datetime('now','localtime')));CREATE TABLE purchase_cost_allocation_items (id INTEGER PRIMARY KEY AUTOINCREMENT,allocation_id INTEGER NOT NULL,receipt_item_id INTEGER NOT NULL,product_id INTEGER NOT NULL,allocated_cost INTEGER NOT NULL);"
 o=run("chown www-data:www-data /tmp/p73-* && runuser -u www-data -- php /tmp/p73-seed.php && "+f"sqlite3 {DB} \"{schema}\" && install -o www-data -g www-data -m 0644 /tmp/p73-r.php {rp} && install -o www-data -g www-data -m 0644 /tmp/p73-h.php {hp} && install -o www-data -g www-data -m 0644 /tmp/p73-v.php {vp} && php -l {rp} && php -l {hp} && php -l {vp} && rm -f /tmp/p73-*")
 print('BACKUP='+B);print('LINT='+o);print('HOME='+run("curl -s -o /dev/null -w '%{http_code}' https://coolingsystems.vn/"));print('P86='+run(f"sqlite3 -separator '|' {DB} \"SELECT capability,permission_code FROM rbac_capability_rules WHERE permission_code='P86';\""))
except Exception:
 run(f"test -f {B}/cooling.db && sqlite3 {DB} \".restore '{B}/cooling.db'\";test -f {B}/admin.php && cp {B}/admin.php {rp};test -f {B}/head.php && cp {B}/head.php {hp};rm -f {vp} /tmp/p73-*;chown www-data:www-data {DB} {rp} {hp}");c.close();raise
c.close()
