import sys
from datetime import datetime
from pathlib import Path
import paramiko
sys.stdout.reconfigure(encoding='utf-8');ROOT=Path('cooling-php/_vps_live');APP='/opt/coolingsystems';DB='/var/lib/coolingsystems/cooling.db';c=paramiko.SSHClient();c.set_missing_host_key_policy(paramiko.AutoAddPolicy());c.connect('103.97.134.164',username='root',password='lcBFDjVF15',timeout=30)
def run(x):
 _,o,e=c.exec_command(x,timeout=90);a=o.read().decode('utf-8','replace');b=e.read().decode('utf-8','replace')
 if o.channel.recv_exit_status():raise RuntimeError(x+'\n'+a+b)
 return a.strip()
def rd(p):
 s=c.open_sftp();f=s.open(p,'rb');v=f.read().decode('utf-8');f.close();s.close();return v
def wr(p,v):
 s=c.open_sftp();f=s.open(p,'wb');f.write(v.encode('utf-8'));f.close();s.close()
stamp=datetime.now().strftime('%Y%m%d-%H%M%S');B=f'/var/backups/coolingsystems/purchase-receipts-phase71-{stamp}';rp=APP+'/routes/admin.php';hp=APP+'/views/partials/dashboard-head.php';vp=APP+'/views/admin/purchase-receipts.php';marker="get('/admin/warranties', function() {"
routes=r'''get('/admin/purchase-receipts',function(){$u=requireStaffPermission('rbac:purchasing.receipts.create|tax_config','/admin/login');$orders=dbAll("SELECT po.id,po.code,s.name AS supplier_name FROM purchase_orders po INNER JOIN suppliers s ON s.id=po.supplier_id WHERE po.status IN ('approved','partially_received') ORDER BY po.created_at DESC");$selectedPo=max(0,(int)($_GET['po']??0));$selectedOrder=$selectedPo?dbGet("SELECT po.*,s.name AS supplier_name FROM purchase_orders po INNER JOIN suppliers s ON s.id=po.supplier_id WHERE po.id=? AND po.status IN ('approved','partially_received')",[$selectedPo]):null;$orderLines=$selectedOrder?dbAll('SELECT * FROM purchase_order_items WHERE order_id=? ORDER BY id',[$selectedPo]):[];$receipts=dbAll("SELECT gr.*,po.code AS po_code,s.name AS supplier_name,COUNT(gri.id) AS line_count FROM goods_receipts gr INNER JOIN purchase_orders po ON po.id=gr.order_id INNER JOIN suppliers s ON s.id=po.supplier_id LEFT JOIN goods_receipt_items gri ON gri.receipt_id=gr.id GROUP BY gr.id ORDER BY gr.created_at DESC LIMIT 200");view('admin/purchase-receipts',['title'=>'Nhận hàng theo PO','userRole'=>'admin','orders'=>$orders,'selectedPo'=>$selectedPo,'selectedOrder'=>$selectedOrder,'orderLines'=>$orderLines,'receipts'=>$receipts]);});
post('/admin/purchase-receipts',function(){$u=requireStaffPermission('rbac:purchasing.receipts.create|tax_config','/admin/login');csrfCheck();$oid=(int)($_POST['order_id']??0);$date=trim($_POST['received_date']??'');$note=trim($_POST['note']??'');$qty=$_POST['qty']??[];if(!$oid||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||mb_strlen($note)>500||!is_array($qty)){flash('error','Dữ liệu nhận hàng không hợp lệ.');redirect('/admin/purchase-receipts');}$pdo=db();try{$pdo->beginTransaction();$po=dbGet("SELECT * FROM purchase_orders WHERE id=? AND status IN ('approved','partially_received')",[$oid]);if(!$po)throw new RuntimeException('po');$lines=[];foreach($qty as $id=>$raw){$id=(int)$id;$n=(int)preg_replace('/\D/','',(string)$raw);if($n<1)continue;$line=dbGet('SELECT * FROM purchase_order_items WHERE id=? AND order_id=?',[$id,$oid]);if(!$line||$n>((int)$line['ordered_qty']-(int)$line['received_qty']))throw new RuntimeException('qty');$lines[]=[$line,$n];}if(!$lines)throw new RuntimeException('qty');$code='PNH-'.date('Ymd-His').'-'.random_int(100,999);$rid=dbInsert("INSERT INTO goods_receipts (code,order_id,received_date,status,note,created_by) VALUES (?,?,?,'pending_qc',?,?)",[$code,$oid,$date,$note,$u['id']]);foreach($lines as [$line,$n]){dbInsert('INSERT INTO goods_receipt_items (receipt_id,order_item_id,product_id,received_qty) VALUES (?,?,?,?)',[$rid,$line['id'],$line['product_id'],$n]);dbRun('UPDATE purchase_order_items SET received_qty=received_qty+? WHERE id=?',[$n,$line['id']]);}$remaining=(int)(dbGet('SELECT COALESCE(SUM(ordered_qty-received_qty),0) AS n FROM purchase_order_items WHERE order_id=?',[$oid])['n']??0);dbRun('UPDATE purchase_orders SET status=? WHERE id=?',[$remaining===0?'received':'partially_received',$oid]);dbRun("INSERT INTO audit_logs (user_id,role,action,entity_type,entity_id,meta,ip,user_agent) VALUES (?,?,?,?,?,?,?,?)",[$u['id'],$u['role']??'admin','goods_receipt_created','goods_receipt',$rid,json_encode(['po'=>$po['code'],'remaining'=>$remaining],JSON_UNESCAPED_UNICODE),$_SERVER['REMOTE_ADDR']??'',$_SERVER['HTTP_USER_AGENT']??'']);$pdo->commit();flash('success','Đã ghi nhận phiếu '.$code.' chờ kiểm chất lượng.');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('error',$e->getMessage()==='qty'?'Số lượng nhận vượt quá số còn lại của PO.':'Không thể ghi nhận hàng về.');}redirect('/admin/purchase-receipts?po='.$oid);});
'''
try:
 run(f"mkdir -p {B} && sqlite3 {DB} \".backup '{B}/cooling.db'\" && cp {rp} {B}/admin.php && cp {hp} {B}/head.php")
 if run(f"sqlite3 {DB} \"SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='goods_receipts';\"")!='0':raise RuntimeError('P84 table exists')
 r=rd(rp)
 if r.count(marker)!=1 or 'goods_receipt_created' in r:raise RuntimeError('route marker')
 wr('/tmp/p71-r.php',r.replace(marker,routes+marker,1));h=rd(hp);old='<a href="/admin/purchase-requests" class="<?= startsWith(currentPath(),\'/admin/purchase-requests\')?\'active\':\'\' ?>"><?= sbIcon(\'list\') ?>Y&#234;u c&#7847;u mua</a>';new=old+'<?php if($__isAdmin || ($__sbU && function_exists(\'rbacCan\') && rbacCan((int)$__sbU[\'id\'],\'purchasing.receipts.create\'))): ?><a href="/admin/purchase-receipts" class="<?= startsWith(currentPath(),\'/admin/purchase-receipts\')?\'active\':\'\' ?>"><?= sbIcon(\'list\') ?>Nh&#7853;n h&#224;ng PO</a><?php endif; ?>'
 if h.count(old)!=1:raise RuntimeError('menu marker')
 wr('/tmp/p71-h.php',h.replace(old,new,1));s=c.open_sftp();s.put(str(ROOT/'purchase-receipts_phase71.php'),'/tmp/p71-v.php');s.close();wr('/tmp/p71-seed.php',"<?php $p=new PDO('sqlite:"+DB+"');$p->prepare('INSERT OR REPLACE INTO rbac_capability_rules (capability,permission_code,allowed_levels) VALUES (?,?,?)')->execute(['purchasing.receipts.create','P84',json_encode(['TQ','QL','TH'])]);")
 schema="ALTER TABLE purchase_order_items ADD COLUMN received_qty INTEGER NOT NULL DEFAULT 0;CREATE TABLE goods_receipts (id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT NOT NULL UNIQUE,order_id INTEGER NOT NULL,received_date TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending_qc',note TEXT,created_by INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT (datetime('now','localtime')));CREATE TABLE goods_receipt_items (id INTEGER PRIMARY KEY AUTOINCREMENT,receipt_id INTEGER NOT NULL,order_item_id INTEGER NOT NULL,product_id INTEGER NOT NULL,received_qty INTEGER NOT NULL CHECK(received_qty>0),accepted_qty INTEGER NOT NULL DEFAULT 0,rejected_qty INTEGER NOT NULL DEFAULT 0);"
 o=run("chown www-data:www-data /tmp/p71-* && runuser -u www-data -- php /tmp/p71-seed.php && "+f"sqlite3 {DB} \"{schema}\" && install -o www-data -g www-data -m 0644 /tmp/p71-r.php {rp} && install -o www-data -g www-data -m 0644 /tmp/p71-h.php {hp} && install -o www-data -g www-data -m 0644 /tmp/p71-v.php {vp} && php -l {rp} && php -l {hp} && php -l {vp} && rm -f /tmp/p71-*")
 print('BACKUP='+B);print('LINT='+o);print('HOME='+run("curl -s -o /dev/null -w '%{http_code}' https://coolingsystems.vn/"));print('P84='+run(f"sqlite3 -separator '|' {DB} \"SELECT capability,permission_code FROM rbac_capability_rules WHERE permission_code='P84';\""))
except Exception:
 run(f"test -f {B}/cooling.db && sqlite3 {DB} \".restore '{B}/cooling.db'\";test -f {B}/admin.php && cp {B}/admin.php {rp};test -f {B}/head.php && cp {B}/head.php {hp};rm -f {vp} /tmp/p71-*;chown www-data:www-data {DB} {rp} {hp}");c.close();raise
c.close()
