<?php require __DIR__ . '/../partials/dashboard-head.php'; ?>
<?php $labels=['received'=>'Tiếp nhận','checking'=>'Đang kiểm tra','approved'=>'Đã duyệt','assigned'=>'Đã phân công','in_progress'=>'Đang xử lý','completed'=>'Đã nghiệm thu','rejected'=>'Từ chối']; ?>
<div class="dash-head"><h1>Bảo hành & Kỹ thuật</h1></div>
<?php foreach(getFlash() as $message): ?><div class="alert alert-<?= e($message['type']) ?>"><?= e($message['message']) ?></div><?php endforeach; ?>
<div class="panel" style="padding:18px;margin-bottom:16px"><h2 style="font-size:16px;margin:0 0 14px;color:var(--navy)">Tạo phiếu bảo hành</h2><form method="post" action="/admin/warranties" style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px"><?= csrfField() ?>
<div class="form-group"><label>Sản phẩm *</label><select name="product_id" required><option value="">Chọn sản phẩm</option><?php foreach($products as $product): ?><option value="<?= (int)$product['id'] ?>"><?= e($product['sku'].' - '.$product['name']) ?></option><?php endforeach; ?></select></div>
<div class="form-group"><label>Tên khách hàng *</label><input name="customer_name" required></div><div class="form-group"><label>Số điện thoại *</label><input name="customer_phone" required></div>
<div class="form-group"><label>Ngày mua</label><input type="date" name="purchase_date" value="<?= date('Y-m-d') ?>"></div><div class="form-group"><label>Số serial (nếu có)</label><input name="serial_no"></div><div class="form-group"><label>Mã đơn hàng (nếu có)</label><input name="order_code"></div>
<div class="form-group" style="grid-column:1/-1"><label>Nội dung yêu cầu *</label><textarea name="issue_description" required rows="3" style="width:100%"></textarea></div><div><button class="btn btn-navy">Tạo phiếu</button></div></form></div>
<div class="panel"><div style="padding:14px 16px;border-bottom:1px solid var(--line);font-weight:700">Danh sách phiếu bảo hành (<?= count($cases) ?>)</div><div style="overflow:auto"><table class="tbl"><thead><tr><th>Mã phiếu</th><th>Sản phẩm</th><th>Khách hàng</th><th>Hạn bảo hành</th><th>Trạng thái</th><th>Cập nhật</th></tr></thead><tbody><?php foreach($cases as $case): ?><tr><td><strong><?= e($case['case_code']) ?></strong><div class="fs-11 text-muted"><?= e($case['serial_no']?:'Không có serial') ?></div></td><td><?= e($case['product_name']) ?><div class="fs-11 text-muted"><?= e($case['sku']) ?></div></td><td><?= e($case['customer_name']) ?><div class="fs-11 text-muted"><?= e($case['customer_phone']) ?></div></td><td><?= e($case['warranty_end_date']) ?></td><td><span style="font-size:11px;font-weight:700;color:#1565c0"><?= e($labels[$case['status']]??$case['status']) ?></span></td><td><form method="post" action="/admin/warranties/<?= (int)$case['id'] ?>/status" style="display:flex;gap:6px;align-items:center"><?= csrfField() ?><select name="status"><?php foreach($labels as $key=>$label): ?><option value="<?= $key ?>" <?= $case['status']===$key?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select><button class="btn btn-sm btn-outline-navy">Lưu</button></form></td></tr><?php endforeach; ?><?php if(!$cases): ?><tr><td colspan="6" style="text-align:center;padding:28px;color:#667085">Chưa có phiếu bảo hành.</td></tr><?php endif; ?></tbody></table></div></div>
<?php require __DIR__ . '/../partials/dashboard-foot.php'; ?>
