CREATE TABLE products (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  partner_id      INTEGER NOT NULL REFERENCES partners(id) ON DELETE CASCADE,
  sku             TEXT    NOT NULL,
  oem_code        TEXT,
  part_brand      TEXT,
  category_id     INTEGER NOT NULL REFERENCES categories(id),
  name            TEXT    NOT NULL,
  slug            TEXT    NOT NULL,
  description     TEXT    NOT NULL,
  short_specs     TEXT,
  price           INTEGER NOT NULL,
  original_price  INTEGER,
  stock           INTEGER NOT NULL DEFAULT 0,
  reserved_stock  INTEGER NOT NULL DEFAULT 0,
  weight_g        INTEGER,
  width_cm        INTEGER,
  height_cm       INTEGER,
  depth_cm        INTEGER,
  status          TEXT    NOT NULL DEFAULT 'draft'
                          CHECK (status IN ('draft','pending','published','hidden','out_of_stock','rejected','blocked')),
  reject_reason   TEXT,
  is_admin_created INTEGER NOT NULL DEFAULT 0,
  is_featured     INTEGER NOT NULL DEFAULT 0,
  is_hot          INTEGER NOT NULL DEFAULT 0,
  is_new          INTEGER NOT NULL DEFAULT 0,
  sold_count      INTEGER NOT NULL DEFAULT 0,
  view_count      INTEGER NOT NULL DEFAULT 0,
  rating_avg      REAL    NOT NULL DEFAULT 0,
  rating_count    INTEGER NOT NULL DEFAULT 0,
  warranty_months INTEGER NOT NULL DEFAULT 6,
  approved_by     INTEGER REFERENCES users(id),
  approved_at     TEXT,
  published_at    TEXT,
  created_at      TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at      TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')), meta_title TEXT, meta_description TEXT, focus_keyword TEXT, canonical_url TEXT, og_image TEXT, is_indexed INTEGER DEFAULT 1, price_before_tax INTEGER DEFAULT 0, tax_amount INTEGER DEFAULT 0, vat_rate INTEGER DEFAULT 10, oem_code2 TEXT, min_stock INTEGER DEFAULT 5, max_stock INTEGER DEFAULT 1000, features TEXT, specifications TEXT, car_brand_id INTEGER REFERENCES brands(id), sale_price INTEGER DEFAULT 0, is_on_sale INTEGER DEFAULT 0, show_on_home INTEGER DEFAULT 0, show_on_promo INTEGER DEFAULT 0, seo_title TEXT DEFAULT '', seo_description TEXT DEFAULT '', seo_keyword TEXT DEFAULT '', video_url TEXT, cost_price INTEGER DEFAULT 0, total_import_value INTEGER DEFAULT 0, location_code TEXT, is_call_price INTEGER DEFAULT 0, is_active INTEGER DEFAULT 1, wholesale_price INTEGER DEFAULT 0,
  UNIQUE(partner_id, sku)
);
