-- Categories Seed
DELETE FROM categories;
INSERT INTO categories VALUES ('11', NULL, 'Két Nước', 'ket-nuoc', NULL, '2', '0', '0', '0');
INSERT INTO categories VALUES ('21', NULL, 'Dàn Sưởi Điều Hòa', 'dan-suoi', NULL, '3', '0', '104', '1');
INSERT INTO categories VALUES ('22', NULL, 'Lốc Điều Hòa', 'loc-dieu-hoa', NULL, '4', '0', '655', '1');
INSERT INTO categories VALUES ('23', NULL, 'Van Tiết Lưu', 'van-tiet-luu', NULL, '6', '0', '194', '1');
INSERT INTO categories VALUES ('24', NULL, 'Van Đuôi Lốc', 'van-duoi-loc', NULL, '7', '0', '140', '1');
INSERT INTO categories VALUES ('25', NULL, 'Motor, Quạt Dàn Nóng', 'motor-quat-dan-nong', NULL, '8', '0', '166', '1');
INSERT INTO categories VALUES ('26', NULL, 'Motor, Quạt Dàn Lạnh', 'motor-quat-dan-lanh', NULL, '9', '0', '414', '1');
INSERT INTO categories VALUES ('27', NULL, 'Phin Lọc Ga', 'phin-loc-ga', NULL, '10', '0', '34', '1');
INSERT INTO categories VALUES ('31', '11', 'Ket Nuoc Con', 'ket-nuoc-con', NULL, '1', '0', '0', '0');
INSERT INTO categories VALUES ('41', NULL, 'Ống dẫn gas điều hòa', 'ong-dan-gas-dieu-hoa', NULL, '12', '0', '121', '1');
INSERT INTO categories VALUES ('42', NULL, 'Mô tơ quạt gió điều hòa', 'mo-to-quat-gio-dieu-hoa', NULL, '13', '0', '0', '1');
INSERT INTO categories VALUES ('43', NULL, 'Dàn nóng điều hòa', 'dan-nong-dieu-hoa', NULL, '14', '0', '382', '1');
INSERT INTO categories VALUES ('44', NULL, 'Cảm biến áp suất gas', 'cam-bien-ap-suat-gas', NULL, '15', '0', '87', '1');
INSERT INTO categories VALUES ('45', NULL, 'Van tiết lưu điều hòa', 'van-tiet-luu-dieu-hoa', NULL, '16', '0', '0', '1');
INSERT INTO categories VALUES ('46', NULL, 'Dàn lạnh điều hòa', 'dan-lanh-dieu-hoa', NULL, '17', '0', '538', '1');
INSERT INTO categories VALUES ('47', NULL, 'Lọc Gió Điều Hòa', 'loc-gio-dieu-hoa', NULL, '11', '0', '0', '1');
INSERT INTO categories VALUES ('48', NULL, 'Điều Hòa Điện & Phụ kiện', 'dieu-hoa-dien-phu-kien', '', '1', '1', '0', '1');
INSERT INTO categories VALUES ('49', NULL, 'Bộ đầu lốc điều hòa', 'bo-dau-loc-dieu-hoa', '', '5', '0', '0', '1');
